/**
 * shared/workflow-actions/tariff-tracker.js
 *
 * Email-driven workflow for Tariff & Oversized Shipment Tracker extraction.
 * Processes FedEx customs invoice PDFs from bizops@orangetsunami.com,
 * performs OT lookups, and emails completed tracker to operator.
 *
 * See: Business Ops/tsk-tariff-tracker-extraction/tariff-tracker-extraction.md
 */

'use strict';

const breadcrumbs = require('../breadcrumbs');

// ─── CONSTANTS ────────────────────────────────────────────────────────────────

const OUTPUT_RECIPIENT = 'justin.oberhofer@astutegroup.com';

// ─── EMAIL HELPER ─────────────────────────────────────────────────────────────

/**
 * Send email via notifier, throwing on failure.
 */
async function sendEmailOrThrow(notifier, to, subject, body, opts = {}) {
  const sent = await notifier.sendEmail(to, subject, body, opts);
  if (!sent) {
    throw new Error(`Failed to send notification email to ${to}: ${subject}`);
  }
  return sent;
}

// ─── HANDLERS ─────────────────────────────────────────────────────────────────

/**
 * Process extracted tariff data and generate tracker.
 *
 * Required payload:
 *   - invoices: Array of extracted invoice records
 *   - outputPath: Path to generated .xlsx file
 *   - subject: Original email subject
 *   - reviewFlags: Array of rows flagged for manual review (optional)
 *
 * The agent extracts PDF data, performs OT lookups, generates the Excel file,
 * then routes here with the completed payload.
 */
async function action_process(payload, ctx) {
  const { invoices, outputPath, subject, reviewFlags } = payload;

  if (ctx.dryRun) {
    return {
      dry_run: true,
      would_email: OUTPUT_RECIPIENT,
      invoice_count: invoices ? invoices.length : 0,
      review_flags: reviewFlags ? reviewFlags.length : 0,
    };
  }

  // Build confirmation email
  const reviewNote = reviewFlags && reviewFlags.length > 0
    ? `\n\n**${reviewFlags.length} row(s) flagged for manual review** — see [REVIEW: ...] comments in SOURCE column.`
    : '';

  const html = `<html><body style="font-family:Arial,sans-serif;font-size:13px">
<h2>Tariff Tracker — Processing Complete</h2>
<p><b>Original email:</b> ${esc(subject)}</p>
<p><b>Invoices processed:</b> ${invoices ? invoices.length : 0}</p>
${reviewNote ? `<p style="color:#b00">${esc(reviewNote)}</p>` : ''}
<p>The completed tracker is attached.</p>
<p style="color:#666;font-size:11px">Generated by tariff-tracker workflow.</p>
</body></html>`;

  // Send with attachment
  await sendEmailOrThrow(
    ctx.notifier,
    OUTPUT_RECIPIENT,
    `Tariff Tracker Complete: ${subject || '(no subject)'}`,
    html,
    {
      html: true,
      attachments: outputPath ? [{ path: outputPath }] : [],
    },
  );

  breadcrumbs.write({
    cog: ctx.workflow,
    event: 'processed',
    uid: ctx.uid,
    invoiceCount: invoices ? invoices.length : 0,
    reviewFlags: reviewFlags ? reviewFlags.length : 0,
    outputPath,
  });

  return {
    emailed: OUTPUT_RECIPIENT,
    invoiceCount: invoices ? invoices.length : 0,
    reviewFlags: reviewFlags ? reviewFlags.length : 0,
  };
}

/**
 * Flag for manual review — extraction failed or ambiguous.
 *
 * Required payload: { reason }
 * Optional: { subject, details }
 */
async function action_needs_review(payload, ctx) {
  const { reason, subject, details } = payload;

  const html = `<html><body style="font-family:Arial,sans-serif;font-size:13px">
<h2 style="color:#b00">Tariff Tracker — Needs Manual Review</h2>
<p><b>Subject:</b> ${esc(subject)}<br/>
   <b>UID:</b> ${ctx.uid}</p>
<p><b>Reason:</b> ${esc(reason)}</p>
${details ? `<pre style="background:#f5f5f5;padding:8px;white-space:pre-wrap;font-size:11px">${esc(details)}</pre>` : ''}
<p style="color:#666;font-size:11px">Message moved to NeedsReview folder.</p>
</body></html>`;

  if (ctx.dryRun) {
    return { dry_run: true, would_notify: OUTPUT_RECIPIENT, reason };
  }

  await sendEmailOrThrow(
    ctx.notifier,
    OUTPUT_RECIPIENT,
    `Tariff Tracker — needs review: ${subject || '(no subject)'}`,
    html,
    { html: true },
  );

  breadcrumbs.write({
    cog: ctx.workflow,
    event: 'needs-review',
    uid: ctx.uid,
    reason,
  });

  return { notified: OUTPUT_RECIPIENT };
}

/**
 * Skip — email not relevant (no PDFs, wrong document type).
 *
 * Required payload: { reason }
 */
async function action_skip(payload, ctx) {
  if (ctx.dryRun) {
    return { dry_run: true, reason: payload.reason || 'unspecified' };
  }

  breadcrumbs.write({
    cog: ctx.workflow,
    event: 'skip',
    uid: ctx.uid,
    reason: payload.reason || 'unspecified',
  });

  return { reason: payload.reason || 'unspecified' };
}

// ─── HELPERS ──────────────────────────────────────────────────────────────────

function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, c =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// ─── EXPORTS ──────────────────────────────────────────────────────────────────

module.exports = {
  inbox: 'bizops@orangetsunami.com',
  notifierConfig: {
    fromEmail: 'bizops@orangetsunami.com',
    fromName: 'Tariff Tracker',
  },
  actions: {
    process: {
      folder: 'Processed',
      requires: ['invoices', 'outputPath'],
      handler: action_process,
    },
    needs_review: {
      folder: 'NeedsReview',
      requires: ['reason'],
      handler: action_needs_review,
    },
    skip: {
      folder: 'Skipped',
      requires: ['reason'],
      handler: action_skip,
    },
  },
};
