#!/usr/bin/env node
/**
 * install-crons.js — regenerate `crontab` from cron-jobs.js registry.
 *
 * Replaces the `analytics_user` crontab with one cron-runner-wrapped line
 * per registry entry. Preserves the PGUSER + LOGNAME env-var header
 * (load-bearing for Postgres peer auth — see crontab.md).
 *
 * Idempotent: safe to re-run any time. The Resilience Checklist is printed
 * for every entry.
 *
 * Usage:
 *   node scripts/install-crons.js          # preview only (no changes)
 *   node scripts/install-crons.js --apply  # actually install
 */

'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execSync } = require('child_process');

const REGISTRY = require('../cron-jobs');
const { installCron, cadenceToMs } = require('../cron-jobs');

const RUNNER_PATH = path.resolve(__dirname, 'cron-runner.js');
const NODE = '/usr/bin/node';

// ─── Crontab header — load-bearing env vars + provenance comment ────────────
const HEADER = [
  '# AUTO-GENERATED by scripts/install-crons.js — do not hand-edit.',
  '# To change scheduled activities, update cron-jobs.js and re-run install.',
  '# Drift check at session start will surface any out-of-band edits.',
  '',
  '# Required for cron jobs touching Postgres (peer-auth — see crontab.md).',
  '# PGDATABASE is load-bearing: pg_hba peer-auth is per-DB, and without it',
  '# psql under cron fails with "fe_sendauth: no password supplied" even when',
  '# PGUSER is set. Discovered 2026-05-04 from offer-poller-excess failures.',
  'PGUSER=analytics_user',
  'LOGNAME=analytics_user',
  'PGDATABASE=idempiere_replica',
  '',
];

function buildCronLine(job) {
  const schedule = installCron(job);
  const logRedirect = `>> "${job.logFile}" 2>&1`;
  return `${schedule} ${NODE} "${RUNNER_PATH}" --job=${job.name} ${logRedirect}`;
}

function buildCrontabBody() {
  const lines = [...HEADER];
  for (const job of REGISTRY) {
    if (typeof job !== 'object' || !job.name) continue; // skip helper exports
    lines.push(`# ${job.name}: ${job.description}`);
    lines.push(buildCronLine(job));
    lines.push('');
  }
  return lines.join('\n');
}

function printResilienceChecklist(job) {
  const otGate = job.needsOT ? 'yes — health-gated' : 'no — independent of OT';
  const subHourly = /^every \d+m$/.test(job.cadence);
  const fixed = job.cadence === 'fixed';
  let catchup;
  if (subHourly) catchup = 'n/a — sub-hourly self-heals';
  else if (fixed) catchup = 'no — fires at exact cron times only';
  else catchup = 'yes — sentinel-gated';
  const installSched = installCron(job);
  console.log('');
  console.log(`  Scheduling activity: ${job.name}`);
  console.log(`  Resilience checklist:`);
  console.log(`    • Cadence:           ${job.cadence}`);
  console.log(`    • Registered in:     cron-jobs.js (not raw crontab)`);
  console.log(`    • Cron schedule:     ${installSched}`);
  console.log(`    • OT-write?:         ${otGate}`);
  console.log(`    • Catch-up on miss?: ${catchup}`);
  console.log(`    • Idempotent?:       NEEDS REVIEW (verify before first run)`);
  console.log(`    • Visibility:        drift check at session start; log → ${job.logFile}`);
}

function main() {
  const apply = process.argv.includes('--apply');

  // Show plan
  console.log('============================================================');
  console.log('CRON INSTALLER — Resilience Checklist for each scheduled job');
  console.log('============================================================');
  for (const job of REGISTRY) {
    if (typeof job !== 'object' || !job.name) continue;
    printResilienceChecklist(job);
  }

  const newCrontab = buildCrontabBody();
  console.log('');
  console.log('============================================================');
  console.log('PROPOSED CRONTAB');
  console.log('============================================================');
  console.log(newCrontab);

  if (!apply) {
    console.log('--- Preview only. Re-run with --apply to install. ---');
    return;
  }

  // Backup current crontab
  let current = '';
  try {
    current = execSync('crontab -l', { encoding: 'utf8' });
  } catch (err) {
    current = '';
  }
  const backupPath = path.join(os.homedir(), 'workspace', `.crontab-backup-${Date.now()}.txt`);
  fs.writeFileSync(backupPath, current);
  console.log('');
  console.log(`Previous crontab backed up to: ${backupPath}`);

  // Install new crontab
  const tmpPath = path.join(os.tmpdir(), `cron-install-${Date.now()}.txt`);
  fs.writeFileSync(tmpPath, newCrontab);
  execSync(`crontab "${tmpPath}"`, { stdio: 'inherit' });
  fs.unlinkSync(tmpPath);

  console.log('');
  console.log('✓ Installed. Verify with `crontab -l`.');
}

main();
